### ISSUE TITLE
Token de Seguridad

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/tunel#2]
Es necesario programar la renovación automática del Token de Seguridad, para evitar el vencimiento e inactivación del sistema

**Comment by gesaodin** [comment]
Para la creación del certificado de seguridad deben realizarse los siguientes pasos:

1. Ir al directorio /home/tunel/sys/seguridad/https; 
2. Borrar los documentos cert.pem y key.pem
3. ejecutar el comando: go run /home/tunel/app/go/src/crypto/tls/generate_cert.go --host=localhost
4. Compilar el tunel nuevamente.
5. Iniciar la aplicación
